# flatpack.toml
# WIP (2023-05-25)

version = "0.0.5"
base_image = "debian:stable-slim"

[environment]
model_name = "nanogpt-shakespeare"

[[port]]
external = 8080
internal = 80

[directories]
checkpoints = "/home/content/checkpoints"
data = "/home/content/data"
models = "/home/content/models"
scripts = "/home/content/scripts"

[packages]

[packages.unix]
gcc = "*"
git = "*"
python3-pip = "*"
wget = "*"

[packages.python]
datasets = "*"
numpy = "*"
tiktoken = "*"
transformers = "*"
torch = "*"
tqdm = "*"
wandb = "*"

[[git]]
from_source = "https://github.com/romlingroup/nanoGPT"
to_destination = "/home/content/nanoGPT"
branch = "master" # You can use this or the tag field, but not both at the same time.
#tag = "v1.0" # You can use this or the branch field, but not both at the same time.

[[dataset]]
from_source = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
to_destination = "/home/content/data/input.txt"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/nanogpt-shakespeare/train.sh"
to_destination = "/home/content/train.sh"

[[run]]
command = "python3"
args = "/home/content/nanoGPT/data/shakespeare_char/prepare.py"

[[run]]

command = "chmod"
args = "+x /home/content/train.sh"

[[cmd]]
command = "bash"
args = "/home/content/train.sh"