# flatpack.toml
# WIP (2023-06-17)

version = "0.0.1"
base_image = "debian:stable-slim"

[environment]
model_name = "roop"

[[port]]
external = 8080
internal = 80

[directories]
checkpoints = "/home/content/checkpoints"
data = "/home/content/data"
models = "/home/content/models"
scripts = "/home/content/scripts"

[packages]

[packages.unix]
gcc = "*"
git = "*"
ffmpeg = "*"
python3-pip = "*"
wget = "*"

[packages.python]
datasets = "*"
numpy = "*"
tiktoken = "*"
transformers = "*"
torch = "*"
tqdm = "*"
wandb = "*"

[[git]]
from_source = "https://github.com/romlingroup/roop"
to_destination = "/home/content/roop"
branch = "main"

[[cmd]]
command = "python"
args = "/home/content/roop/run.py"