# flatpack.toml
# WIP ({{current_date}})

version = "0.0.1"

[environment]
model_name = "moondream"

[[port]]
external = 8080
internal = 80

[directories]
checkpoints = "checkpoints"
data = "data"
models = "models"
scripts = "scripts"

[packages]

[packages.unix]
build-essential = "*"
gcc = "*"
git = "*"
python3-dev = "*"
python3-pip = "*"
wget = "*"

[packages.python]
numpy = "2.0.1"
tiktoken = "0.7.0"
tqdm = "4.66.4"

[[git]]
from_source = "https://github.com/vikhyat/moondream"
to_destination = "moondream"
branch = "main"
# setup_commands = [
#   "{{setup_command}}"
# ]

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/moondream/index.html"
to_destination = "index.html"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/moondream/build.sh"
to_destination = "build.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/moondream/custom.sh"
to_destination = "custom.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/moondream/device.sh"
to_destination = "device.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/moondream/tiger.png"
to_destination = "tiger.png"

[[run]]
command = "chmod +x"
file = "build.sh"

[[run]]
command = "chmod +x"
file = "custom.sh"

[[run]]
command = "chmod +x"
file = "device.sh"