# flatpack.toml
# WIP (2024-03-09)

version = "0.0.1"

[environment]
model_name = "moondream"

[[port]]
external = 1337
internal = 80

[directories]
checkpoints = "/home/content/checkpoints"
data = "/home/content/data"
models = "/home/content/models"
scripts = "/home/content/scripts"

[packages]

[packages.unix]
build-essential = "*"
gcc = "*"
git = "*"
python3-dev = "*"
python3-pip = "*"
wget = "*"

[packages.python]
datasets = "2.19.0"
numpy = "1.25.2"
tiktoken = "0.6.0"
transformers = "4.36.2"
tqdm = "4.66.2"

[[git]]
from_source = "https://github.com/vikhyat/moondream"
to_destination = "/home/content/moondream"
branch = "main"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/moondream/tiger.png"
to_destination = "/home/content/tiger.png"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/moondream/device.sh"
to_destination = "/home/content/device.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/moondream/build.sh"
to_destination = "/home/content/build.sh"

[[run]]
command = "chmod"
args = "+x /home/content/device.sh"

[[run]]
command = "chmod"
args = "+x /home/content/build.sh"

[[cmd]]
command = "bash"
args = "/home/content/build.sh"