# flatpack.toml
# WIP (2024-03-09)

version = "0.0.1"

[environment]
model_name = "moondream"

[[port]]
external = 1337
internal = 80

[directories]
checkpoints = "checkpoints"
data = "data"
models = "models"
scripts = "scripts"

[packages]

[packages.unix]
build-essential = "*"
gcc = "*"
git = "*"
python3-dev = "*"
python3-pip = "*"
wget = "*"

[packages.python]
numpy = "1.25.2"
tiktoken = "0.6.0"
tqdm = "4.66.2"

[[git]]
from_source = "https://github.com/vikhyat/moondream"
to_destination = "moondream"
branch = "main"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/moondream/tiger.png"
to_destination = "tiger.png"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/moondream/device.sh"
to_destination = "device.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/moondream/build.sh"
to_destination = "build.sh"

[[run]]
command = "chmod +x"
file = "device.sh"

[[run]]
command = "chmod +x"
file = "build.sh"

[[cmd]]
command = "bash"
file = "build.sh"