# flatpack.toml
# WIP ({{current_date}})

version = "0.0.1"

[environment]
model_name = "edge-model"

[[port]]
external = 1337
internal = 80

[directories]
checkpoints = "/home/content/checkpoints"
data = "/home/content/data"
models = "/home/content/models"
scripts = "/home/content/scripts"

[packages]

[packages.unix]
gcc = "*"
git = "*"
python3-pip = "*"
wget = "*"

[packages.python]
datasets = "*"
numpy = "*"
tiktoken = "*"
transformers = "*"
torch = "*"
tqdm = "*"
wandb = "*"

# [[git]]
# from_source = "{{git_source_url}}"
# to_destination = "{{git_destination_dir}}"
# branch = "{{branch_name}}"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/edge-model/device.sh"
to_destination = "/home/content/device.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/edge-model/train.sh"
to_destination = "/home/content/train.sh"

[[run]]
command = "chmod"
args = "+x /home/content/device.sh"

[[run]]
command = "chmod"
args = "+x /home/content/train.sh"

[[cmd]]
command = "bash"
args = "/home/content/train.sh"