# flatpack.toml
# WIP ({{current_date}})

version = "0.0.1"
base_image = "debian:stable-slim"

[environment]
model_name = "edge-model"

[[port]]
external = 1337
internal = 80

[directories]
checkpoints = "/home/content/checkpoints"
data = "/home/content/data"
models = "/home/content/models"
scripts = "/home/content/scripts"

[packages]

[packages.unix]
gcc = "*"
git = "*"
python3-pip = "*"
wget = "*"

[packages.python]
datasets = "*"
numpy = "*"
tiktoken = "*"
transformers = "*"
torch = "*"
tqdm = "*"
wandb = "*"

[[git]]
from_source = "{{git_source_url}}"
to_destination = "{{git_destination_dir}}"
branch = "{{branch_name}}"

[[file]]
from_source = "{{file_source_url}}"
to_destination = "{{file_destination_path}}"

[[run]]
command = "{{run_command}}"
args = "{{run_args}}"

[[cmd]]
command = "{{cmd_command}}"
args = "{{cmd_args}}"