# flatpack.toml
# WIP ({{current_date}})

version = "0.0.1"

[environment]
model_name = "phi-3-mlx"

[[port]]
external = 8080
internal = 80

[directories]
checkpoints = "checkpoints"
data = "data"
models = "models"
scripts = "scripts"

[packages]

[packages.unix]
build-essential = "*"
gcc = "*"
git = "*"
jq = "*"
python3-dev = "*"
python3-pip = "*"
sox = "*"
wget = "*"

[packages.python]
numpy = "2.0.1"
tiktoken = "0.7.0"
tqdm = "4.66.5"

[[git]]
from_source = "https://github.com/JosefAlbers/Phi-3-Vision-MLX"
to_destination = "Phi-3-Vision-MLX"
branch = "main"
setup_commands = [
    "../bin/pip install -e ."
]

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/phi-3-mlx/custom.json"
to_destination = "custom.json"

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/phi-3-mlx/build.sh"
to_destination = "build.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/phi-3-mlx/device.sh"
to_destination = "device.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/phi-3-mlx/tiger.png"
to_destination = "tiger.png"

[[run]]
command = "chmod +x"
file = "build.sh"

[[run]]
command = "chmod +x"
file = "device.sh"