# flatpack.toml
# WIP ({{current_date}})

version = "0.0.1"

[environment]
model_name = "flux-1-schnell"

[[port]]
external = 8080
internal = 80

[directories]
checkpoints = "checkpoints"
data = "data"
models = "models"
scripts = "scripts"

[packages]

[packages.unix]
build-essential = "*"
gcc = "*"
git = "*"
jq = "*"
python3-dev = "*"
python3-pip = "*"
sox = "*"
wget = "*"

[packages.python]
diffusers = "0.30.3"
numpy = "2.0.1"
tiktoken = "0.7.0"
tqdm = "4.66.5"
transformers = "4.45.2"

[[git]]
from_source = "https://github.com/leejet/stable-diffusion.cpp"
to_destination = "stable-diffusion.cpp"
branch = "master"
setup_commands = [
    "git pull origin master",
    "git submodule init",
    "git submodule update"
]

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/flux-1-schnell/custom.json"
to_destination = "custom.json"

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/flux-1-schnell/build.sh"
to_destination = "build.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/flux-1-schnell/device.sh"
to_destination = "device.sh"

[[run]]
command = "chmod +x"
file = "build.sh"

[[run]]
command = "chmod +x"
file = "device.sh"