# flatpack.toml
# WIP (2023-06-28)

version = "0.0.1"
base_image = "debian:stable-slim"

[environment]
model_name = "lit-gpt-falcon"

[[port]]
external = 1337
internal = 80

[directories]
checkpoints = "/home/content/checkpoints"
data = "/home/content/data"
models = "/home/content/models"
scripts = "/home/content/scripts"

[packages]

[packages.unix]
gcc = "*"
git = "*"
python3-pip = "*"
wget = "*"

[[git]]
from_source = "https://github.com/romlingroup/lit-gpt"
to_destination = "/home/content/lit-gpt"
branch = "main"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/lit-gpt-falcon/train.sh"
to_destination = "/home/content/train.sh"

[[run]]
command = "pip"
args = "install huggingface_hub"

[[run]]
command = "pip"
args = "install --index-url https://download.pytorch.org/whl/nightly/cu118 --pre 'torch>=2.1.0dev'"

[[run]]
command = "pip"
args = "uninstall -y torchaudio"

[[run]]
command = "chmod"
args = "+x /home/content/train.sh"

[[cmd]]
command = "bash"
args = "/home/content/train.sh"