# flatpack.toml
# WIP ({{current_date}})

version = "0.0.1"

[environment]
model_name = "minicpm-llama3"

[[port]]
external = 8080
internal = 80

[directories]
checkpoints = "checkpoints"
data = "data"
models = "models"
scripts = "scripts"

[packages]

[packages.unix]
build-essential = "*"
gcc = "*"
git = "*"
jq = "*"
python3-dev = "*"
python3-pip = "*"
sox = "*"
wget = "*"

[packages.python]
numpy = "2.0.1"
tiktoken = "0.7.0"
tqdm = "4.66.5"

[[git]]
from_source = "https://github.com/OpenBMB/llama.cpp.git"
to_destination = "llama.cpp"
branch = "minicpm-v2.5"
setup_commands = [
    "../bin/pip install setuptools[distutils]",
    "make",
    "make minicpmv-cli"
]

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/minicpm-llama3/build.sh"
to_destination = "build.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/minicpm-llama3/custom.sh"
to_destination = "custom.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/minicpm-llama3/device.sh"
to_destination = "device.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/minicpm-llama3/tiger.png"
to_destination = "tiger.png"

[[run]]
command = "chmod +x"
file = "build.sh"

[[run]]
command = "chmod +x"
file = "custom.sh"

[[run]]
command = "chmod +x"
file = "device.sh"