# flatpack.toml
# WIP (2023-06-09)

version = "0.0.1"
base_image = "debian:stable-slim"

[environment]
model_name = "nanogpt-gpt2"

[[port]]
external = 8080
internal = 80

[directories]
checkpoints = "/home/content/checkpoints"
data = "/home/content/data"
models = "/home/content/models"
scripts = "/home/content/scripts"

[packages]

[packages.unix]
gcc = "*"
git = "*"
python3-pip = "*"
wget = "*"

[packages.python]
datasets = "*"
numpy = "*"
tiktoken = "*"
transformers = "*"
torch = "*"
tqdm = "*"
wandb = "*"

[[git]]
from_source = "https://github.com/romlingroup/nanoGPT"
to_destination = "/home/content/nanoGPT"
branch = "cuda-availability"

[[dataset]]
from_source = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
to_destination = "/home/content/data/input.txt"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/nanogpt-gpt2/train.sh"
to_destination = "/home/content/train.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/nanogpt-gpt2/finetune_shakespeare.py"
to_destination = "/home/content/nanoGPT/config/finetune_shakespeare.py"

[[run]]
command = "python"
args = "/home/content/nanoGPT/data/shakespeare/prepare.py"

[[run]]
command = "chmod"
args = "+x /home/content/train.sh"

[[cmd]]
command = "bash"
args = "/home/content/train.sh"