# flatpack.toml
# WIP ({{current_date}})

version = "0.0.1"

[environment]
model_name = "real-time-vision"

[[port]]
external = 1337
internal = 80

[directories]
checkpoints = "checkpoints"
data = "data"
models = "models"
scripts = "scripts"

[packages]

[packages.unix]
build-essential = "*"
gcc = "*"
git = "*"
python3-dev = "*"
python3-pip = "*"
wget = "*"

[packages.python]
einops = "0.8.0"
mss = "9.0.1"
numpy = "1.25.2"
opencv-python = "4.9.0.80"
tiktoken = "0.6.0"
tqdm = "4.66.2"
transformers = "4.40.2"

[[git]]
from_source = "https://github.com/vikhyat/moondream"
to_destination = "moondream"
branch = "main"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/real-time-vision/index.html"
to_destination = "index.html"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/real-time-vision/build.sh"
to_destination = "build.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/real-time-vision/custom.sh"
to_destination = "custom.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/real-time-vision/device.sh"
to_destination = "device.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/real-time-vision/init.sh"
to_destination = "init.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/real-time-vision/capture.py"
to_destination = "capture.py"

[[run]]
command = "chmod +x"
file = "build.sh"

[[run]]
command = "chmod +x"
file = "custom.sh"

[[run]]
command = "chmod +x"
file = "device.sh"

[[run]]
command = "chmod +x"
file = "init.sh"

[[cmd]]
command = "bash"
file = "build.sh"