# flatpack.toml
# WIP (2023-05-21)

version = "0.0.1"
license = "apache-2.0"
base_image = "nvidia/cuda:12.1.1-base-ubuntu22.04"

[environment]
model_name = "custom-gpt"

[[port]]
external = 8080
internal = 80

[directories]
checkpoints = "/home/content/checkpoints"
data = "/home/content/data"
models = "/home/content/models"
scripts = "/home/content/scripts"

[packages]

[packages.unix]
build-essential = "*"
curl = "*"
git = "*"
python3-pip = "*"
wget = "*"
unzip = "*"

[packages.python]
keras = "*"
matplotlib = "*"
nltk = "*"
numpy = "*"
pandas = "*"
plotly = "*"
scikit-learn = "*"
seaborn = "*"
spacy = "*"
tensorflow = "*"
torch = "*"

[[dataset]]
from_source = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
to_destination = "/home/content/data/input.txt"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/custom-gpt/main.py"
to_destination = "/home/content/scripts/main.py"

[[git]]
from_source = "https://github.com/karpathy/nanoGPT"
to_destination = "/home/content/nanoGPT"

[[script]]
command = "python3"
file = "/home/content/scripts/main.py"