# flatpack.toml
# WIP (2023-05-23)

version = "0.0.4"
license = "apache-2.0"
base_image = "python:3.11-slim-buster"

[environment]
model_name = "custom-gpt"

[[port]]
external = 8080
internal = 80

[directories]
checkpoints = "/home/content/checkpoints"
data = "/home/content/data"
models = "/home/content/models"
scripts = "/home/content/scripts"

[packages]

[packages.unix]
curl = "*"
git = "*"
wget = "*"
unzip = "*"

[packages.python]
datasets = "*"
numpy = "*"
tiktoken = "*"
transformers = "*"
torch = "*"
tqdm = "*"
wandb = "*"

[[dataset]]
from_source = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
to_destination = "/home/content/data/input.txt"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/custom-gpt/train.sh"
to_destination = "/home/content/train.sh"

[[git]]
from_source = "https://github.com/karpathy/nanoGPT"
to_destination = "/home/content/nanoGPT"

[[run]]
command = "python3"
args = "/home/content/nanoGPT/data/shakespeare_char/prepare.py"

[[run]]
command = "chmod"
args = "+x /home/content/train.sh"

[[cmd]]
command = "bash"
args = "/home/content/train.sh"