# flatpack.toml
# WIP (2023-05-10)

# Version number
version = "0.0.1"

# License information
license = "apache-2.0"

# Base image
base_image = "nvidia/cuda:12.1.1-base-ubuntu22.04"

# Environment variables
[environment]
model_name = "custom-gpt"

# Port settings
[[port]]
external = 8080
internal = 80

# Directory paths
[directories]
checkpoints = "/home/content/checkpoints"
data = "/home/content/data"
models = "/home/content/models"
scripts = "/home/content/scripts"

# Package dependencies
[packages]

[packages.unix]
build-essential = "*"
curl = "*"
git = "*"
python3-pip = "*"
wget = "*"
unzip = "*"

[packages.python]
keras = "*"
matplotlib = "*"
nltk = "*"
numpy = "*"
pandas = "*"
plotly = "*"
scikit-learn = "*"
seaborn = "*"
spacy = "*"
tensorflow = "*"
torch = "*"

# Dataset downloads
[[dataset]]
from_source = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
to_destination = "/home/content/data/input.txt"

# File downloads
[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/custom-gpt/main.py"
to_destination = "/home/content/scripts/main.py"

# Entrypoint
[entrypoint]
command = "python"
file = "/home/content/scripts/main.py"