# flatpack.toml
# WIP (2023-05-23)

version = "0.0.2"
license = "apache-2.0"
base_image = "ubuntu:20.04"

[environment]
model_name = "custom-gpt"

[[port]]
external = 8080
internal = 80

[directories]
checkpoints = "/home/content/checkpoints"
data = "/home/content/data"
models = "/home/content/models"
scripts = "/home/content/scripts"

[packages]

[packages.unix]
build-essential = "*"
curl = "*"
git = "*"
python3-pip = "*"
wget = "*"
unzip = "*"

[packages.python]
datasets = "*"
numpy = "*"
tiktoken = "*"
transformers = "*"
torch = "*"
tqdm = "*"
wandb = "*"

[[dataset]]
from_source = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
to_destination = "/home/content/data/input.txt"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/custom-gpt/main.py"
to_destination = "/home/content/scripts/main.py"

[[git]]
from_source = "https://github.com/karpathy/nanoGPT"
to_destination = "/home/content/nanoGPT"

[[run]]
command = "python3"
args = "data/shakespeare_char/prepare.py"
working_directory = "/home/content/nanoGPT"

[[cmd]]
command = "python3"
args = "train.py config/train_shakespeare_char.py --device=cpu --compile=False --eval_iters=20 --log_interval=1 --block_size=64 --batch_size=12 --n_layer=4 --n_head=4 --n_embd=128 --max_iters=2000 --lr_decay_iters=2000 --dropout=0.0"
working_directory = "/home/content/nanoGPT"