# flatpack.toml
# WIP ({{current_date}})

version = "0.0.1"

[environment]
model_name = "{{model_name}}"

[[port]]
external = 1337
internal = 80

[directories]
checkpoints = "checkpoints"
data = "data"
models = "models"
scripts = "scripts"

[packages]

[packages.unix]
build-essential = "*"
gcc = "*"
git = "*"
python3-dev = "*"
python3-pip = "*"
wget = "*"

[packages.python]
numpy = "1.25.2"
tiktoken = "0.6.0"
tqdm = "4.66.2"

# [[git]]
# from_source = "{{git_source_url}}"
# to_destination = "{{git_destination_dir}}"
# branch = "{{branch_name}}"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/{{model_name}}/device.sh"
to_destination = "device.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/{{model_name}}/build.sh"
to_destination = "build.sh"

[[run]]
command = "chmod +x"
args = "device.sh"

[[run]]
command = "chmod +x"
args = "build.sh"

[[cmd]]
command = "bash"
args = "build.sh"