# flatpack.toml
# WIP ({{current_date}})

version = "0.0.1"

[environment]
model_name = "mediapipe"

[[port]]
external = 8080
internal = 80

[directories]
checkpoints = "checkpoints"
data = "data"
models = "models"
scripts = "scripts"

[packages]

[packages.unix]
build-essential = "*"
gcc = "*"
git = "*"
jq = "*"
python3-dev = "*"
python3-pip = "*"
sox = "*"
wget = "*"

[packages.python]
mediapipe = "0.10.15"
numpy = "1.26.4"
opencv-python = "4.10.0.84"
tiktoken = "0.7.0"
tqdm = "4.66.5"

[[git]]
from_source = "https://github.com/google-ai-edge/mediapipe"
to_destination = "mediapipe"
branch = "master"
# setup_commands = [
#   "{{setup_command}}"
# ]

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/mediapipe/custom.json"
to_destination = "custom.json"

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/mediapipe/build.sh"
to_destination = "build.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/mediapipe/device.sh"
to_destination = "device.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/RomlinGroup/Flatpack/main/warehouse/mediapipe/cat_and_dog.png"
to_destination = "cat_and_dog.png"

[[run]]
command = "chmod +x"
file = "build.sh"

[[run]]
command = "chmod +x"
file = "device.sh"