# flatpack.toml
# WIP (2023-06-22)

version = "0.0.1"
base_image = "debian:stable-slim"

[environment]
model_name = "lit-parrot-redpajama"

[[port]]
external = 8080
internal = 80

[directories]
checkpoints = "/home/content/checkpoints"
data = "/home/content/data"
models = "/home/content/models"
scripts = "/home/content/scripts"

[packages]

[packages.unix]
gcc = "*"
git = "*"
python3-pip = "*"
wget = "*"

[[git]]
from_source = "https://github.com/Lightning-AI/lit-gpt"
to_destination = "/home/content/lit-gpt"
branch = "main"