# flatpack.toml
# WIP ({{current_date}})

version = "0.0.1"

[environment]
model_name = "mini-omni"

[[port]]
external = 8080
internal = 80

[directories]
checkpoints = "checkpoints"
data = "data"
models = "models"
scripts = "scripts"

[packages]

[packages.unix]
build-essential = "*"
gcc = "*"
git = "*"
jq = "*"
python3-dev = "*"
python3-pip = "*"
sox = "*"
wget = "*"

[packages.python]
numpy = "2.0.1"
tiktoken = "0.7.0"
tqdm = "4.66.5"

[[git]]
from_source = "https://github.com/gpt-omni/mini-omni"
to_destination = "mini-omni"
branch = "main"
# setup_commands = [
#   "{{setup_command}}"
# ]

[[file]]
from_source = "build.sh"
to_destination = "build.sh"

[[file]]
from_source = "custom.sh"
to_destination = "custom.sh"

[[file]]
from_source = "device.sh"
to_destination = "device.sh"

[[run]]
command = "chmod +x"
file = "build.sh"

[[run]]
command = "chmod +x"
file = "custom.sh"

[[run]]
command = "chmod +x"
file = "device.sh"