# flatpack.toml
# WIP ({{current_date}})

version = "0.0.1"

[environment]
model_name = "phi-3-vision"

[[port]]
external = 1337
internal = 80

[directories]
checkpoints = "checkpoints"
data = "data"
models = "models"
scripts = "scripts"

[packages]

[packages.unix]
build-essential = "*"
gcc = "*"
git = "*"
python3-dev = "*"
python3-pip = "*"
wget = "*"

[packages.python]
gradio = "4.31.5"
numpy = "1.24.4"
Pillow = "10.3.0"
Requests = "2.31.0"
tiktoken = "0.6.0"
transformers = "4.40.2"
tqdm = "4.66.2"

# [[git]]
# from_source = "{{git_source_url}}"
# to_destination = "{{git_destination_dir}}"
# branch = "{{branch_name}}"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/phi-3-vision/index.html"
to_destination = "index.html"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/phi-3-vision/build.sh"
to_destination = "build.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/phi-3-vision/custom.sh"
to_destination = "custom.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/phi-3-vision/device.sh"
to_destination = "device.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/phi-3-vision/init.sh"
to_destination = "init.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/phi-3-vision/gradio.py"
to_destination = "gradio.py"

[[run]]
command = "chmod +x"
file = "build.sh"

[[run]]
command = "chmod +x"
file = "custom.sh"

[[run]]
command = "chmod +x"
file = "device.sh"

[[run]]
command = "chmod +x"
file = "init.sh"

[[cmd]]
command = "bash"
file = "build.sh"