# flatpack.toml
# WIP (2024-03-09)

version = "0.0.1"

[environment]
model_name = "styletts2"

[[port]]
external = 1337
internal = 80

[directories]
checkpoints = "/home/content/checkpoints"
data = "/home/content/data"
models = "/home/content/models"
scripts = "/home/content/scripts"

[packages]

[packages.unix]
build-essential = "*"
gcc = "*"
git = "*"
python3-dev = "*"
python3-pip = "*"
wget = "*"

[packages.python]
datasets = "*"
numpy = "*"
tiktoken = "*"
transformers = "*"
torch = "*"
tqdm = "*"
wandb = "*"
styletts2 = "0.1.6"

[[git]]
from_source = "https://github.com/sidharthrajaram/StyleTTS2"
to_destination = "/home/content/StyleTTS2"
branch = "main"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/styletts2/device.sh"
to_destination = "/home/content/device.sh"

[[file]]
from_source = "https://raw.githubusercontent.com/romlingroup/flatpack-ai/main/warehouse/styletts2/build.sh"
to_destination = "/home/content/build.sh"

[[run]]
command = "chmod"
args = "+x /home/content/device.sh"

[[run]]
command = "chmod"
args = "+x /home/content/build.sh"

[[cmd]]
command = "bash"
args = "/home/content/build.sh"