name: Compress and Sign FPK
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  compress_and_sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flatpack

      - name: Remove existing FPK files
        run: |
          find . -name "*.fpk" -type f -delete

      - name: Create FPK packages
        run: |
          for d in warehouse/*/; do
            if [ -d "$d" ]; then
              echo "Processing directory: $d"
              flatpack pack "$d"
              # Move the created FPK file into the directory
              mv "${d%/}.fpk" "$d"
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add warehouse/**/*.fpk
          git commit -m "Updated FPK files"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}